/* eslint-disable max-lines -- we want ALL THE LICENSES */
/** One selectable OSI license option. */
export type SigilLicenseOption = Readonly<{
  id: string;
  name: string;
  spdxId: string | undefined;
  label: string;
  value: string;
}>;

/** Generated OSI license options used by the sigil browser tool. */
export const OSI_LICENSE_OPTIONS: ReadonlyArray<SigilLicenseOption> = [
  {
    id: "apache-2-0",
    label: "Apache License, Version 2.0 (Apache-2.0)",
    name: "Apache License, Version 2.0",
    spdxId: "Apache-2.0",
    value: "Apache-2.0",
  },
  {
    id: "bsd-1-clause",
    label: "1-clause BSD License (BSD-1-Clause)",
    name: "1-clause BSD License",
    spdxId: "BSD-1-Clause",
    value: "BSD-1-Clause",
  },
  {
    id: "afl-3-0",
    label: "Academic Free License v. 3.0 (AFL-3.0)",
    name: "Academic Free License v. 3.0",
    spdxId: "AFL-3.0",
    value: "AFL-3.0",
  },
  {
    id: "apl-1-0",
    label: "Adaptive Public License 1.0 (APL-1.0)",
    name: "Adaptive Public License 1.0",
    spdxId: "APL-1.0",
    value: "APL-1.0",
  },
  {
    id: "apache-1-1",
    label: "Apache Software License, version 1.1 (Apache-1.1)",
    name: "Apache Software License, version 1.1",
    spdxId: "Apache-1.1",
    value: "Apache-1.1",
  },
  {
    id: "apsl-2-0",
    label: "Apple Public Source License 2.0 (APSL-2.0)",
    name: "Apple Public Source License 2.0",
    spdxId: "APSL-2.0",
    value: "APSL-2.0",
  },
  {
    id: "artistic-1-0-perl",
    label: "Artistic License (Perl) 1.0 (Artistic-1.0-Perl)",
    name: "Artistic License (Perl) 1.0",
    spdxId: "Artistic-1.0-Perl",
    value: "Artistic-1.0-Perl",
  },
  {
    id: "artistic-1-0",
    label: "Artistic License 1.0 (Artistic-1.0)",
    name: "Artistic License 1.0",
    spdxId: "Artistic-1.0",
    value: "Artistic-1.0",
  },
  {
    id: "artistic-2-0",
    label: "Artistic License 2.0 (Artistic-2.0)",
    name: "Artistic License 2.0",
    spdxId: "Artistic-2.0",
    value: "Artistic-2.0",
  },
  {
    id: "aal",
    label: "Attribution Assurance License (AAL)",
    name: "Attribution Assurance License",
    spdxId: "AAL",
    value: "AAL",
  },
  {
    id: "blueoak-1-0-0",
    label: "Blue Oak Model License (BlueOak-1.0.0)",
    name: "Blue Oak Model License",
    spdxId: "BlueOak-1.0.0",
    value: "BlueOak-1.0.0",
  },
  {
    id: "bsl-1-0",
    label: "Boost Software License 1.0 (BSL-1.0)",
    name: "Boost Software License 1.0",
    spdxId: "BSL-1.0",
    value: "BSL-1.0",
  },
  {
    id: "bsd-3-clause-open-mpi",
    label: "BSD-3-Clause-Open-MPI (BSD-3-Clause-Open-MPI)",
    name: "BSD-3-Clause-Open-MPI",
    spdxId: "BSD-3-Clause-Open-MPI",
    value: "BSD-3-Clause-Open-MPI",
  },
  {
    id: "bsd-2-clause-patent",
    label: "BSD+Patent (BSD-2-Clause-Patent)",
    name: "BSD+Patent",
    spdxId: "BSD-2-Clause-Patent",
    value: "BSD-2-Clause-Patent",
  },
  {
    id: "cecill-2-1",
    label: "Cea Cnrs Inria Logiciel Libre License, version 2.1 (CECILL-2.1)",
    name: "Cea Cnrs Inria Logiciel Libre License, version 2.1",
    spdxId: "CECILL-2.1",
    value: "CECILL-2.1",
  },
  {
    id: "cern-ohl-p-2-0",
    label: "CERN Open Hardware Licence Version 2 - Permissive (CERN-OHL-P-2.0)",
    name: "CERN Open Hardware Licence Version 2 - Permissive",
    spdxId: "CERN-OHL-P-2.0",
    value: "CERN-OHL-P-2.0",
  },
  {
    id: "cern-ohl-s-2-0",
    label:
      "CERN Open Hardware Licence Version 2 - Strongly Reciprocal (CERN-OHL-S-2.0 )",
    name: "CERN Open Hardware Licence Version 2 - Strongly Reciprocal",
    spdxId: "CERN-OHL-S-2.0 ",
    value: "CERN-OHL-S-2.0 ",
  },
  {
    id: "cern-ohl-w-2-0",
    label:
      "CERN Open Hardware Licence Version 2 - Weakly Reciprocal (CERN-OHL-W-2.0)",
    name: "CERN Open Hardware Licence Version 2 - Weakly Reciprocal",
    spdxId: "CERN-OHL-W-2.0",
    value: "CERN-OHL-W-2.0",
  },
  {
    id: "mit-cmu",
    label: "CMU License (MIT-CMU)",
    name: "CMU License",
    spdxId: "MIT-CMU",
    value: "MIT-CMU",
  },
  {
    id: "cddl-1-1",
    label: "COMMON DEVELOPMENT AND DISTRIBUTION LICENSE (CDDL) (CDDL-1.1)",
    name: "COMMON DEVELOPMENT AND DISTRIBUTION LICENSE (CDDL)",
    spdxId: "CDDL-1.1",
    value: "CDDL-1.1",
  },
  {
    id: "cddl-1-0",
    label: "Common Development and Distribution License 1.0 (CDDL-1.0)",
    name: "Common Development and Distribution License 1.0",
    spdxId: "CDDL-1.0",
    value: "CDDL-1.0",
  },
  {
    id: "cpal-1-0",
    label: "Common Public Attribution License Version 1.0 (CPAL-1.0)",
    name: "Common Public Attribution License Version 1.0",
    spdxId: "CPAL-1.0",
    value: "CPAL-1.0",
  },
  {
    id: "cpl-1-0",
    label: "Common Public License Version 1.0 (CPL-1.0)",
    name: "Common Public License Version 1.0",
    spdxId: "CPL-1.0",
    value: "CPL-1.0",
  },
  {
    id: "catosl-1-1",
    label: "Computer Associates Trusted Open Source License 1.1 (CATOSL-1.1)",
    name: "Computer Associates Trusted Open Source License 1.1",
    spdxId: "CATOSL-1.1",
    value: "CATOSL-1.1",
  },
  {
    id: "cal-1-0",
    label: "Cryptographic Autonomy License (CAL-1.0)",
    name: "Cryptographic Autonomy License",
    spdxId: "CAL-1.0",
    value: "CAL-1.0",
  },
  {
    id: "cua-opl-1-0",
    label: "CUA Office Public License (CUA-OPL-1.0)",
    name: "CUA Office Public License",
    spdxId: "CUA-OPL-1.0",
    value: "CUA-OPL-1.0",
  },
  {
    id: "epl-1-0",
    label: "Eclipse Public License -v 1.0 (EPL-1.0)",
    name: "Eclipse Public License -v 1.0",
    spdxId: "EPL-1.0",
    value: "EPL-1.0",
  },
  {
    id: "epl-2-0",
    label: "Eclipse Public License version 2.0 (EPL-2.0)",
    name: "Eclipse Public License version 2.0",
    spdxId: "EPL-2.0",
    value: "EPL-2.0",
  },
  {
    id: "ecos-2-0",
    label: "eCos License version 2.0 (eCos-2.0)",
    name: "eCos License version 2.0",
    spdxId: "eCos-2.0",
    value: "eCos-2.0",
  },
  {
    id: "ecl-1-0",
    label: "Educational Community License, Version 1.0 (ECL-1.0)",
    name: "Educational Community License, Version 1.0",
    spdxId: "ECL-1.0",
    value: "ECL-1.0",
  },
  {
    id: "ecl-2-0",
    label: "Educational Community License, Version 2.0 (ECL-2.0)",
    name: "Educational Community License, Version 2.0",
    spdxId: "ECL-2.0",
    value: "ECL-2.0",
  },
  {
    id: "efl-1-0",
    label: "Eiffel Forum License, version 1 (EFL-1.0)",
    name: "Eiffel Forum License, version 1",
    spdxId: "EFL-1.0",
    value: "EFL-1.0",
  },
  {
    id: "efl-2-0",
    label: "Eiffel Forum License, Version 2 (EFL-2.0)",
    name: "Eiffel Forum License, Version 2",
    spdxId: "EFL-2.0",
    value: "EFL-2.0",
  },
  {
    id: "entessa",
    label: "Entessa Public License Version. 1.0 (Entessa)",
    name: "Entessa Public License Version. 1.0",
    spdxId: "Entessa",
    value: "Entessa",
  },
  {
    id: "eudatagrid",
    label: "EU DataGrid Software License (EUDatagrid)",
    name: "EU DataGrid Software License",
    spdxId: "EUDatagrid",
    value: "EUDatagrid",
  },
  {
    id: "eupl-1-2",
    label: "European Union Public Licence, version 1.2 (EUPL-1.2)",
    name: "European Union Public Licence, version 1.2",
    spdxId: "EUPL-1.2",
    value: "EUPL-1.2",
  },
  {
    id: "fair",
    label: "Fair License (Fair)",
    name: "Fair License",
    spdxId: "Fair",
    value: "Fair",
  },
  {
    id: "frameworx-1-0",
    label: "Frameworx License 1.0 (Frameworx-1.0)",
    name: "Frameworx License 1.0",
    spdxId: "Frameworx-1.0",
    value: "Frameworx-1.0",
  },
  {
    id: "agpl-3-0",
    label: "GNU Affero General Public License version 3 (AGPL-3.0)",
    name: "GNU Affero General Public License version 3",
    spdxId: "AGPL-3.0",
    value: "AGPL-3.0",
  },
  {
    id: "gpl-2-0",
    label: "GNU General Public License version 2 (GPL-2.0)",
    name: "GNU General Public License version 2",
    spdxId: "GPL-2.0",
    value: "GPL-2.0",
  },
  {
    id: "gpl-3-0",
    label: "GNU General Public License version 3 (GPL-3.0)",
    name: "GNU General Public License version 3",
    spdxId: "GPL-3.0",
    value: "GPL-3.0",
  },
  {
    id: "gpl-1-0",
    label: "GNU General Public License, version 1 (GPL-1.0)",
    name: "GNU General Public License, version 1",
    spdxId: "GPL-1.0",
    value: "GPL-1.0",
  },
  {
    id: "lgpl-2-1",
    label: "GNU Lesser General Public License version 2.1 (LGPL-2.1)",
    name: "GNU Lesser General Public License version 2.1",
    spdxId: "LGPL-2.1",
    value: "LGPL-2.1",
  },
  {
    id: "lgpl-3-0",
    label: "GNU Lesser General Public License version 3 (LGPL-3.0)",
    name: "GNU Lesser General Public License version 3",
    spdxId: "LGPL-3.0",
    value: "LGPL-3.0",
  },
  {
    id: "lgpl-2-0",
    label: "GNU Library General Public License version 2 (LGPL-2.0)",
    name: "GNU Library General Public License version 2",
    spdxId: "LGPL-2.0",
    value: "LGPL-2.0",
  },
  {
    id: "hpnd",
    label: "Historical Permission Notice and Disclaimer (HPND)",
    name: "Historical Permission Notice and Disclaimer",
    spdxId: "HPND",
    value: "HPND",
  },
  {
    id: "ipl-1-0",
    label: "IBM Public License Version 1.0 (IPL-1.0)",
    name: "IBM Public License Version 1.0",
    spdxId: "IPL-1.0",
    value: "IPL-1.0",
  },
  {
    id: "icu",
    label: "ICU License (ICU)",
    name: "ICU License",
    spdxId: "ICU",
    value: "ICU",
  },
  {
    id: "intel",
    label: "Intel Open Source License (Intel)",
    name: "Intel Open Source License",
    spdxId: "Intel",
    value: "Intel",
  },
  {
    id: "ipa",
    label: "IPA Font License (IPA)",
    name: "IPA Font License",
    spdxId: "IPA",
    value: "IPA",
  },
  {
    id: "isc",
    label: "ISC License (ISC)",
    name: "ISC License",
    spdxId: "ISC",
    value: "ISC",
  },
  {
    id: "jam",
    label: "JAM License (Jam)",
    name: "JAM License",
    spdxId: "Jam",
    value: "Jam",
  },
  {
    id: "lppl-1-3c",
    label: "LaTeX Project Public License, Version 1.3c (LPPL-1.3c)",
    name: "LaTeX Project Public License, Version 1.3c",
    spdxId: "LPPL-1.3c",
    value: "LPPL-1.3c",
  },
  {
    id: "bsd-3-clause-lbnl",
    label:
      "Lawrence Berkeley National Labs BSD Variant License (BSD-3-Clause-LBNL)",
    name: "Lawrence Berkeley National Labs BSD Variant License",
    spdxId: "BSD-3-Clause-LBNL",
    value: "BSD-3-Clause-LBNL",
  },
  {
    id: "liliq-p-1-1",
    label: "Licence Libre du Québec – Permissive  version 1.1 (LiLiQ-P-1.1)",
    name: "Licence Libre du Québec – Permissive  version 1.1",
    spdxId: "LiLiQ-P-1.1",
    value: "LiLiQ-P-1.1",
  },
  {
    id: "liliq-rplus-1-1",
    label:
      "Licence Libre du Québec – Réciprocité forte version 1.1 (LiLiQ-Rplus-1.1)",
    name: "Licence Libre du Québec – Réciprocité forte version 1.1",
    spdxId: "LiLiQ-Rplus-1.1",
    value: "LiLiQ-Rplus-1.1",
  },
  {
    id: "liliq-r-1-1",
    label: "Licence Libre du Québec – Réciprocité version 1.1 (LiLiQ-R-1.1)",
    name: "Licence Libre du Québec – Réciprocité version 1.1",
    spdxId: "LiLiQ-R-1.1",
    value: "LiLiQ-R-1.1",
  },
  {
    id: "lpl-1-02",
    label: "Lucent Public License Version 1.02 (LPL-1.02)",
    name: "Lucent Public License Version 1.02",
    spdxId: "LPL-1.02",
    value: "LPL-1.02",
  },
  {
    id: "lpl-1-0",
    label: "Lucent Public License, Plan 9, version 1.0 (LPL-1.0)",
    name: "Lucent Public License, Plan 9, version 1.0",
    spdxId: "LPL-1.0",
    value: "LPL-1.0",
  },
  {
    id: "ms-pl",
    label: "Microsoft Public License (MS-PL)",
    name: "Microsoft Public License",
    spdxId: "MS-PL",
    value: "MS-PL",
  },
  {
    id: "ms-rl",
    label: "Microsoft Reciprocal License (MS-RL)",
    name: "Microsoft Reciprocal License",
    spdxId: "MS-RL",
    value: "MS-RL",
  },
  {
    id: "miros",
    label: "MirOS Licence (MirOS)",
    name: "MirOS Licence",
    spdxId: "MirOS",
    value: "MirOS",
  },
  {
    id: "mit-0",
    label: "MIT No Attribution License (MIT-0)",
    name: "MIT No Attribution License",
    spdxId: "MIT-0",
    value: "MIT-0",
  },
  {
    id: "motosoto",
    label: "Motosoto Open Source License (Motosoto)",
    name: "Motosoto Open Source License",
    spdxId: "Motosoto",
    value: "Motosoto",
  },
  {
    id: "mpl-1-1",
    label: "Mozilla Public License 1.1 (MPL-1.1)",
    name: "Mozilla Public License 1.1",
    spdxId: "MPL-1.1",
    value: "MPL-1.1",
  },
  {
    id: "mpl-2-0",
    label: "Mozilla Public License 2.0 (MPL-2.0)",
    name: "Mozilla Public License 2.0",
    spdxId: "MPL-2.0",
    value: "MPL-2.0",
  },
  {
    id: "mpl-1-0",
    label: "Mozilla Public License, version 1.0 (MPL-1.0)",
    name: "Mozilla Public License, version 1.0",
    spdxId: "MPL-1.0",
    value: "MPL-1.0",
  },
  {
    id: "mulanpsl-2-0",
    label: "Mulan Permissive Software License v2 (MulanPSL-2.0)",
    name: "Mulan Permissive Software License v2",
    spdxId: "MulanPSL-2.0",
    value: "MulanPSL-2.0",
  },
  {
    id: "multics",
    label: "Multics License (Multics)",
    name: "Multics License",
    spdxId: "Multics",
    value: "Multics",
  },
  {
    id: "nasa-1-3",
    label: "NASA Open Source Agreement v1.3 (NASA-1.3)",
    name: "NASA Open Source Agreement v1.3",
    spdxId: "NASA-1.3",
    value: "NASA-1.3",
  },
  {
    id: "naumen",
    label: "NAUMEN Public License (Naumen)",
    name: "NAUMEN Public License",
    spdxId: "Naumen",
    value: "Naumen",
  },
  {
    id: "nokia",
    label: "Nokia Open Source License Version 1.0a (NOKIA)",
    name: "Nokia Open Source License Version 1.0a",
    spdxId: "NOKIA",
    value: "NOKIA",
  },
  {
    id: "nposl-3-0",
    label: "Non-Profit Open Software License version 3.0 (NPOSL-3.0)",
    name: "Non-Profit Open Software License version 3.0",
    spdxId: "NPOSL-3.0",
    value: "NPOSL-3.0",
  },
  {
    id: "ntp",
    label: "NTP License (NTP)",
    name: "NTP License",
    spdxId: "NTP",
    value: "NTP",
  },
  {
    id: "ogtsl",
    label: "Open Group Test Suite License (OGTSL)",
    name: "Open Group Test Suite License",
    spdxId: "OGTSL",
    value: "OGTSL",
  },
  {
    id: "olfl-1-3",
    label: "Open Logistics Foundation License v1.3 (OLFL-1.3)",
    name: "Open Logistics Foundation License v1.3",
    spdxId: "OLFL-1.3",
    value: "OLFL-1.3",
  },
  {
    id: "osl-2-1",
    label: "Open Software License 2.1 (OSL-2.1)",
    name: "Open Software License 2.1",
    spdxId: "OSL-2.1",
    value: "OSL-2.1",
  },
  {
    id: "osl-1-0",
    label: "Open Software License, version 1.0 (OSL-1.0)",
    name: "Open Software License, version 1.0",
    spdxId: "OSL-1.0",
    value: "OSL-1.0",
  },
  {
    id: "oldap-2-8",
    label: "OpenLDAP Public License Version 2.8 (OLDAP-2.8)",
    name: "OpenLDAP Public License Version 2.8",
    spdxId: "OLDAP-2.8",
    value: "OLDAP-2.8",
  },
  {
    id: "osc-1-0",
    label: "OSC License 1.0 (OSC-1.0)",
    name: "OSC License 1.0",
    spdxId: "OSC-1.0",
    value: "OSC-1.0",
  },
  {
    id: "oset-pl-2-1",
    label: "OSET Public License version 2.1 (OSET-PL-2.1)",
    name: "OSET Public License version 2.1",
    spdxId: "OSET-PL-2.1",
    value: "OSET-PL-2.1",
  },
  {
    id: "php-3-0",
    label: "PHP License 3.0 (PHP-3.0)",
    name: "PHP License 3.0",
    spdxId: "PHP-3.0",
    value: "PHP-3.0",
  },
  {
    id: "php-3-01",
    label: "PHP License 3.01 (PHP-3.01)",
    name: "PHP License 3.01",
    spdxId: "PHP-3.01",
    value: "PHP-3.01",
  },
  {
    id: "python-2-0",
    label: "Python License, Version 2 (Python-2.0)",
    name: "Python License, Version 2",
    spdxId: "Python-2.0",
    value: "Python-2.0",
  },
  {
    id: "rpsl-1-0",
    label: "RealNetworks Public Source License Version 1.0 (RPSL-1.0)",
    name: "RealNetworks Public Source License Version 1.0",
    spdxId: "RPSL-1.0",
    value: "RPSL-1.0",
  },
  {
    id: "rpl-1-5",
    label: "Reciprocal Public License 1.5 (RPL-1.5)",
    name: "Reciprocal Public License 1.5",
    spdxId: "RPL-1.5",
    value: "RPL-1.5",
  },
  {
    id: "rpl-1-1",
    label: "Reciprocal Public License, version 1.1 (RPL-1.1)",
    name: "Reciprocal Public License, version 1.1",
    spdxId: "RPL-1.1",
    value: "RPL-1.1",
  },
  {
    id: "ofl-1-1",
    label: "SIL OPEN FONT LICENSE (OFL-1.1)",
    name: "SIL OPEN FONT LICENSE",
    spdxId: "OFL-1.1",
    value: "OFL-1.1",
  },
  {
    id: "simpl-2-0",
    label: "Simple Public License (SimPL-2.0)",
    name: "Simple Public License",
    spdxId: "SimPL-2.0",
    value: "SimPL-2.0",
  },
  {
    id: "sissl",
    label: "Sun Industry Standards Source License (SISSL)",
    name: "Sun Industry Standards Source License",
    spdxId: "SISSL",
    value: "SISSL",
  },
  {
    id: "spl-1-0",
    label: "Sun Public License, Version 1.0 (SPL-1.0)",
    name: "Sun Public License, Version 1.0",
    spdxId: "SPL-1.0",
    value: "SPL-1.0",
  },
  {
    id: "bsd-2-clause",
    label: "The 2-Clause BSD License (BSD-2-Clause)",
    name: "The 2-Clause BSD License",
    spdxId: "BSD-2-Clause",
    value: "BSD-2-Clause",
  },
  {
    id: "bsd-3-clause",
    label: "The 3-Clause BSD License (BSD-3-Clause)",
    name: "The 3-Clause BSD License",
    spdxId: "BSD-3-Clause",
    value: "BSD-3-Clause",
  },
  {
    id: "cnri-python",
    label: "The CNRI portion of the multi-part Python License (CNRI-Python)",
    name: "The CNRI portion of the multi-part Python License",
    spdxId: "CNRI-Python",
    value: "CNRI-Python",
  },
  {
    id: "eupl-1-1",
    label: "The European Union Public License, version 1.1 (EUPL-1.1)",
    name: "The European Union Public License, version 1.1",
    spdxId: "EUPL-1.1",
    value: "EUPL-1.1",
  },
  {
    id: "mit",
    label: "The MIT License (MIT)",
    name: "The MIT License",
    spdxId: "MIT",
    value: "MIT",
  },
  {
    id: "ngpl",
    label: "The Nethack General Public License (NGPL)",
    name: "The Nethack General Public License",
    spdxId: "NGPL",
    value: "NGPL",
  },
  {
    id: "oclc-2-0",
    label: "The OCLC Research Public License 2.0 License (OCLC-2.0)",
    name: "The OCLC Research Public License 2.0 License",
    spdxId: "OCLC-2.0",
    value: "OCLC-2.0",
  },
  {
    id: "osl-3-0",
    label: "The Open Software License 3.0 (OSL-3.0)",
    name: "The Open Software License 3.0",
    spdxId: "OSL-3.0",
    value: "OSL-3.0",
  },
  {
    id: "postgresql",
    label: "The PostgreSQL License (PostgreSQL)",
    name: "The PostgreSQL License",
    spdxId: "PostgreSQL",
    value: "PostgreSQL",
  },
  {
    id: "qpl-1-0",
    label: "The Q Public License Version (QPL-1.0)",
    name: "The Q Public License Version",
    spdxId: "QPL-1.0",
    value: "QPL-1.0",
  },
  {
    id: "rscpl",
    label: "The Ricoh Source Code Public License (RSCPL)",
    name: "The Ricoh Source Code Public License",
    spdxId: "RSCPL",
    value: "RSCPL",
  },
  {
    id: "sleepycat",
    label: "The Sleepycat License (Sleepycat)",
    name: "The Sleepycat License",
    spdxId: "Sleepycat",
    value: "Sleepycat",
  },
  {
    id: "watcom-1-0",
    label: "The Sybase Open Source Licence (Watcom-1.0)",
    name: "The Sybase Open Source Licence",
    spdxId: "Watcom-1.0",
    value: "Watcom-1.0",
  },
  {
    id: "upl-1-0",
    label: "The Universal Permissive License Version 1.0 (UPL-1.0)",
    name: "The Universal Permissive License Version 1.0",
    spdxId: "UPL-1.0",
    value: "UPL-1.0",
  },
  {
    id: "ncsa",
    label: "The University of Illinois/NCSA Open Source License (NCSA)",
    name: "The University of Illinois/NCSA Open Source License",
    spdxId: "NCSA",
    value: "NCSA",
  },
  {
    id: "unlicense",
    label: "The Unlicense (Unlicense)",
    name: "The Unlicense",
    spdxId: "Unlicense",
    value: "Unlicense",
  },
  {
    id: "vsl-1-0",
    label: "The Vovida Software License v. 1.0 (VSL-1.0)",
    name: "The Vovida Software License v. 1.0",
    spdxId: "VSL-1.0",
    value: "VSL-1.0",
  },
  {
    id: "w3c-20150513",
    label: "The W3C® Software and Document license (W3C-20150513)",
    name: "The W3C® Software and Document license",
    spdxId: "W3C-20150513",
    value: "W3C-20150513",
  },
  {
    id: "wxwindows",
    label: "The wxWindows Library Licence (wxWindows)",
    name: "The wxWindows Library Licence",
    spdxId: "wxWindows",
    value: "wxWindows",
  },
  {
    id: "xnet",
    label: "The X.Net, Inc. License (Xnet)",
    name: "The X.Net, Inc. License",
    spdxId: "Xnet",
    value: "Xnet",
  },
  {
    id: "zlib",
    label: "The zlib/libpng License (Zlib)",
    name: "The zlib/libpng License",
    spdxId: "Zlib",
    value: "Zlib",
  },
  {
    id: "unicode-3-0",
    label: "UNICODE LICENSE V3 (Unicode-3.0)",
    name: "UNICODE LICENSE V3",
    spdxId: "Unicode-3.0",
    value: "Unicode-3.0",
  },
  {
    id: "unicode-dfs-2016",
    label:
      "Unicode, Inc. License Agreement - Data Files and Software (Unicode-DFS-2016)",
    name: "Unicode, Inc. License Agreement - Data Files and Software",
    spdxId: "Unicode-DFS-2016",
    value: "Unicode-DFS-2016",
  },
  {
    id: "ucl-1-0",
    label: "Upstream Compatibility License v1.0 (UCL-1.0)",
    name: "Upstream Compatibility License v1.0",
    spdxId: "UCL-1.0",
    value: "UCL-1.0",
  },
  {
    id: "wordnet",
    label: "WordNet (WordNet)",
    name: "WordNet",
    spdxId: "WordNet",
    value: "WordNet",
  },
  {
    id: "0bsd",
    label: "Zero-Clause BSD (0BSD)",
    name: "Zero-Clause BSD",
    spdxId: "0BSD",
    value: "0BSD",
  },
  {
    id: "zpl-2-0",
    label: "Zope Public License 2.0 (ZPL-2.0)",
    name: "Zope Public License 2.0",
    spdxId: "ZPL-2.0",
    value: "ZPL-2.0",
  },
  {
    id: "zpl-2-1",
    label: "Zope Public License 2.1 (ZPL-2.1)",
    name: "Zope Public License 2.1",
    spdxId: "ZPL-2.1",
    value: "ZPL-2.1",
  },
];
